create table users (
    id bigint generated by default as identity primary key,
    full_name varchar(120) not null,
    email varchar(180) not null,
    password varchar(255) not null,
    role varchar(40) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(180),
    updated_by varchar(180)
);

alter table users
    add constraint uk_users_email unique (email);

create index ix_users_email on users (email);
create index ix_users_role on users (role);
