create table tasks (
    id bigint generated by default as identity primary key,
    title varchar(160) not null,
    description text,
    owner_id bigint not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(180),
    updated_by varchar(180),
    constraint fk_tasks_owner foreign key (owner_id) references users (id)
);

create index ix_tasks_owner_id on tasks (owner_id);
