create table audit_events (
    id bigint generated by default as identity primary key,
    actor_id bigint,
    action_type varchar(60) not null,
    resource_type varchar(80) not null,
    resource_id varchar(120),
    ip_address varchar(45),
    created_at timestamp with time zone not null default current_timestamp
);
